name: Docker Image CI

on: 
  release:
    types: [created]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag asciidoctor:$(echo $GITHUB_REF | awk -F'/' `{ print $3 }`)
